import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { Toaster } from 'react-hot-toast';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
        <Toaster
          position='top-right'
          toastOptions={{
            duration: 4000,
            style: {
              background: '#1a1a1a',
              color: '#ffda17',
              border: '2px solid #ffda17',
              borderRadius: '4px',
              fontSize: '14px',
              fontWeight: '500'
            },
            success: {
              iconTheme: {
                primary: '#ffda17',
                secondary: '#1a1a1a'
              }
            },
            error: {
              iconTheme: {
                primary: '#ef4444',
                secondary: '#1a1a1a'
              },
              style: {
                border: '2px solid #ef4444',
                color: '#ef4444'
              }
            }
          }}
        />
      </body>
    </html>
  );
}
